version: "3.6"

services:
  hotel:
    container_name: hotel-elmiriam-payment-svc
    image: ranckosolutionsinc/mpesa-api:v2.0
    build: ./
    restart: always
    environment:
      - PORT=8006
    env_file:
      - ./.env
    networks:
      - hotel-elmiriam-network
    # depends_on:
    #   - mongo

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
