version: "3.6"

services:
  checkout:
    container_name: checkout-svc
    image: ranckosolutionsinc/mpesa-api:v2.0-daraja
    build: ./
    restart: always
    environment:
      - PORT=8006
    env_file:
      - ./.env
    networks:
      - checkout-network
    # depends_on:
    #   - mongo

networks:
  checkout-network:
    name: checkout
    driver: bridge
