version: "3"

services:
  mpesa_api:
    build:
      context: .
    ports:
      - "8009:8000"
    volumes:
      - ./:/src
      - mpesa_api-static:/static
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

volumes:
  mpesa_api-static:
